### ISSUE TITLE
Add Icons In Navigation Drawer

### ISSUE THREAD

**Issue by SAITARUN55** [SAITARUN55/metroapp#14]
@shivaniaakanksha Start working on this

**Comment by shivaniaakanksha** [comment]
@SAITARUN55  I'm curious to work on this issue.
https://github.com/SAITARUN55/metroapp/pull/12#issuecomment-602064760
Referring to this can you please more specify the exception in share and feedback.

**Comment by SAITARUN55** [comment]
Will share the screenshots

**Comment by shivaniaakanksha** [comment]
> Will share the screenshots

I got the error I missed the routes for Share and Feedback. Shall I update it, in PR of this issue?
