### ISSUE TITLE
Remove routes and fare from home nav bar

### ISSUE THREAD

**Issue by ShrutiAggarwal99** [SAITARUN55/metroapp#34]
In the home navbar, the Routes and Fare options are not needed. Since they are city-specific so they should in the navbar corresponding to each city.

**Comment by ShrutiAggarwal99** [comment]
@SAITARUN55 Please assign this to me, I want to work on this issue.

**Comment by SAITARUN55** [comment]
Take down metro map too in d home nav bar

**Comment by ShrutiAggarwal99** [comment]
Yes, thanks for pointing out!

**Comment by ShrutiAggarwal99** [comment]
@SAITARUN55 Please review PR #41
