### ISSUE TITLE
Add Splash Screen Image

### ISSUE THREAD

**Issue by SAITARUN55** [SAITARUN55/metroapp#4]

**Comment by Jahnavi-Jonnalagadda** [comment]
HI @SAITARUN55, Could you please let me know what this issue is about? Can I give a try?

**Comment by SAITARUN55** [comment]
@Jahnavi-Jonnalagadda I think you have to wait for 2-3 more days. As @sakshivij is making the App icon. After she makes the App Icon, you can use the same image to implement Splash Screen.

**Comment by Jahnavi-Jonnalagadda** [comment]
Yes, will wait for further instructions.

**Comment by SAITARUN55** [comment]
Okay @Jahnavi-Jonnalagadda

**Comment by SAITARUN55** [comment]
@Jahnavi-Jonnalagadda you can start working now

**Comment by Jahnavi-Jonnalagadda** [comment]
@SAITARUN55 Have installed the Flutter and ran the metroapp in Android Studio Project in my laptop. Able to see metroapp icon and on click of that a splash screen is popped up with images of different cities. Kindly let me know the actual task here?

**Comment by SAITARUN55** [comment]
@Jahnavi-Jonnalagadda When the user opens the app, it should display the splash screen for about 3 to 5 seconds maximum. The App Icon should act as the same for the Image in Splash Screen with White or Yellow Background ( depending on the outline of the image).

**Comment by Jahnavi-Jonnalagadda** [comment]
Okay @SAITARUN55 
Will revert for further queries.

**Comment by ShrutiAggarwal99** [comment]
Hi @SAITARUN55 
I want to work on this issue. Can you assign this to me if this is still open?

**Comment by shilpi1958** [comment]
@SAITARUN55 
I would like to work on this issue. Please assign it to me!

**Comment by shilpi1958** [comment]
@SAITARUN55 
Please review PR #35
