### ISSUE TITLE
Add Navigation Bar

### ISSUE THREAD

**Issue by SAITARUN55** [SAITARUN55/metroapp#5]
Add Navigation Bar and Include options like About App, Places, Share, etc

**Comment by n4i9kita** [comment]
Hi @SAITARUN55 . I want to give a try on this issue. I want to clarify that navigation bar here refers to navigation drawer, appbar or bottombar?

**Comment by SAITARUN55** [comment]
@n4i9kita on app bar, left of it

**Comment by SAITARUN55** [comment]
Will share what all to include by tomorrow

**Comment by n4i9kita** [comment]
Ok sure.Thanks

**Comment by SAITARUN55** [comment]
Do add like these
About
Routes
Fare
Metro Map
Settings
Send Feedback
Share
Rate the app
Privacy Policy
Logout

When clicked on these a new page should be opened and leave it empty.
When u create new dart files, name the files in a way such that it can be understood to anyone very easily

**Comment by n4i9kita** [comment]
ok. sure .
