### ISSUE TITLE
Add Introduction Slider for the application

### ISSUE THREAD

**Issue by SAITARUN55** [SAITARUN55/metroapp#6]

**Comment by maanyavendra** [comment]
@SAITARUN55 I Would like to work on this issue.

**Comment by ShrutiAggarwal99** [comment]
Can you explain this issue @SAITARUN55? I would like to give a try to solve it.

**Comment by ShrutiAggarwal99** [comment]
What features do we need to highlight in the Introduction Slider @SAITARUN55?
