### ISSUE TITLE
Update App Icon

### ISSUE THREAD

**Issue by SAITARUN55** [SAITARUN55/metroapp#7]

**Comment by sakshivij** [comment]
hi @SAITARUN55 I would like to work on this issue. Does this require designing the icon as well?

**Comment by SAITARUN55** [comment]
Hi @sakshivij Yes it requires designing the icon as well

**Comment by sakshivij** [comment]
Oh okay. Can you give me some guidance on how to do that ? I haven't worked with designing icons. Like some tool that you can suggest or anything ?

**Comment by sakshivij** [comment]
Also can I be creative or you suggest some guidelines to be followed ?

**Comment by SAITARUN55** [comment]
Sure @sakshivij You can use Adobe XD for that, which I preferred in my past. But let me know whether you are comfortable using Adobe XD. Yes, you can be creative. Suggestions are welcomed. Please do join the Gitter channel. But the Icon should be Metro only.
If you want to use Google Images, then open the images and click on Tools, then proceed to Usage rights and select "Labelled for Reuse" or "Labelled for Reuse with modification ( if you want to modify using Tools) or 
else go with designing the App Icon from Scratch.

**Comment by sakshivij** [comment]
Thanks! I'll be working on this then

**Comment by SAITARUN55** [comment]
okay, if you are new to Adobe XD, try canva.com or icons8.com/ouch or vecteezy.com for creating designs. Let me also know how much time does it take for you to build this

**Comment by sakshivij** [comment]
sure! I'm new to Adobe XD but I'll try working on it. I might need a day or two to work on this.

**Comment by SAITARUN55** [comment]
Okay, no problem

**Comment by SAITARUN55** [comment]
Any updates?

**Comment by sakshivij** [comment]
Yup. I will be able to submit it today.
